  
version: '3.8'

services:
  frontend:
    image: edwang09/zhaopengyou_frontend
    build: 
      context: ./frontend
      target: ${ENV}
      args:
        - REACT_APP_SERVICES_HOST=/api
    volumes: 
      - ./frontend:/app
      - /app/node_modules
    
    ports:
      - "80:80"
    networks: 
      - frontend
      - backend
    command: npm run start

  backend:
    image: edwang09/zhaopengyou_backend
    build:
      context: ./backend
    volumes: 
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    networks: 
      - backend
    command: npm run dev

networks: 
  frontend:
  backend: